### ISSUE TITLE
extract add on crashes with ES6-style imports

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#158]
If I run the extract add on using the JSX demo, node throws an error:

```
C:\projects\nano-css-extract-demo\demo>node extract.js
C:\projects\nano-css-extract-demo\demo\src\nano.js:1
(function (exports, require, module, __filename, __dirname) { import { createEle
ment } from "react";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\nano-css-extract-demo\demo\extract.js:1:7
6)
```

Can you provide an updated example that uses the JSX demo?

**Comment by streamich** [comment]
Use `require` instead of `import` as Node does not understand it.

```js
const {createElement} = require('react');
```

Or, alternatively, you need to transpile your code before you run Node.

**Comment by streamich** [comment]
Or, instead of running your script with `node` you can run it with TypeScript `ts-node` or Bbable `babel-node`.

**Comment by TheBosZ** [comment]
Thanks! I was able to get it working using babel-node with the env and react presets:
`babel-node --presets=env,react extract.js`
